- name: "[CentOS7,AMZN2] mysql communityレポジトリインストール"
  yum:
    name: https://repo.mysql.com//mysql80-community-release-el7-5.noarch.rpm
    state: present

- name: enable mysql57-community
  shell: |
   yum-config-manager --disable mysql80-community
   yum-config-manager --enable mysql57-community

- name: install mysql-community-client
  yum:
   name: mysql-community-client
   state: present
